import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
       <Image className={styles.logo} src={'/images/x_logo.png'} alt="x logo" width={545} height={487}/>
    <div className={styles.options}>
    <div className={styles.titles}>
        <h1 className={styles.happening}>Happening now</h1>
        <h2 className={styles.join}>Join today.</h2>
    </div>
    <div className={styles.container}>
        <button className={styles.google}>Sign up with Google</button>
        <button className={styles.apple}>Sign up with Apple</button>
    <div className={styles.divide}>
        <div className={styles.leftline}></div>
        <p className={styles.or}>or</p>
        <div className={styles.rightline}></div>
   </div>
        <button className={styles.createaccount}>Create Account</button>
        <p className={styles.agree}>By signing up, you agree to the Terms of Service and Privacy Policy including Cookie Use.</p>
    </div>
    <div className={styles.existinguser}>
        <h3 className={styles.already}>Already have an account?</h3>
        <button className={styles.signin}>Sign In</button>
    </div>
    </div>
    </main>
    <footer className={styles.more}>
        <p className={styles.actions}>About</p>
        <p className={styles.actions}>Download the X app</p>
        <p className={styles.actions}>Help Center</p>
        <p className={styles.actions}>Terms of Service</p>
        <p className={styles.actions}>Privacy Policy</p>
        <p className={styles.actions}>Cookie Policy</p>
        <p className={styles.actions}>Accesibility</p>
        <p className={styles.actions}>Ads Info</p>
        <p className={styles.actions}>Blog</p>
        <p className={styles.actions}>Status</p>
        <p className={styles.actions}>Careers</p>
        <p className={styles.actions}>Brand Resources</p>
        <p className={styles.actions}>Advertising</p>
        <p className={styles.actions}>Marketing</p>
        <p className={styles.actions}>X for Businesses</p>
        <p className={styles.actions}>Developers</p>
        <p className={styles.actions}>Directory</p>
        <p className={styles.actions}>Settings</p>
        <p className={styles.actions}>2024 X Corp.</p>
    </footer>
    </>
  )
}
